package com.smartInvoice.auth_service.domain;

public enum AuthEventType {
	SIGNUP,
	EMAIL_VERIFICATION_SENT,
	EMAIL_VERIFIED,
	LOGIN_SUCCESS,
	LOGIN_FAILURE,
	LOGOUT,
	LOGOUT_ALL,
	TOKEN_REFRESH,
	REFRESH_REUSE_DETECTED,
	PASSWORD_RESET_REQUEST,
	PASSWORD_RESET_SUCCESS,
	PASSWORD_CHANGE_SUCCESS,
	ADMIN_LOGIN_PASSWORD_OK,
	USER_2FA_SENT,
	USER_2FA_SUCCESS,
	USER_2FA_FAILURE,

	// Kept for existing audit log rows created before admin 2FA was removed.
	ADMIN_2FA_SENT,
	ADMIN_2FA_SUCCESS,
	ADMIN_2FA_FAILURE
}
